# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bd9edd846e3a79769330462b27f5b15c81a66177a96dbbf7649ec9fb01cb192a67339aa315bb58e76fbfeba7dae712a3d1ee8369093b818a81ac9f4445afd39

test:
  secret_key_base: 3a5fed9585c3487c0da34bf3038a36a42b1536bae62a63d31d7c3eb5ba5a59f4c9c18444e96a16529556ecde7ad5da63067d951d11f714b4d442a3b974722090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
